export { default as Home } from './Home'
export { default as Test } from './Test'
export { default as Page404 } from './Page404'
export { default as Register } from './Register'
export { default as Layouts } from './Layouts'
export { default as Login } from './Login'
